version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Say hello
          command: echo Hello && sleep 10 && echo Bye
  other-build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Say hello
          command: echo Hello Other && sleep 10 && echo Bye Other
workflows:
  version: 2
  build1:
    jobs:
      - build
