name: matrix

on: push

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        key:
          - foo
          - bar
          - baz
    steps:
      - run: echo '${{ matrix.key }}'
