name: open-backport-pull-request

on:
  push:
    branches:
      - 'main'
      - '*/main'

  workflow_dispatch:
    inputs:
      headBranch:
        description: Target branch to backport from
        required: true

jobs:
  backport:
    runs-on: ubuntu-latest
    env:
      BACKPORT_BASE_BRANCH: 'develop'
    steps:
      - id: backport
        name: Open Backport Pull Request
        uses: quipper/monorepo-deploy-actions/open-backport-pull-request@open-backport-pull-request
        with:
          base-branch: develop
      - name: Show Pull Request URL
        if: ${{ startsWith(steps.backport.outputs.pull-request-url, 'https://') }}
        run: |
          echo "URL: ${{steps.backport.outputs.pull-request-url}}"
